#!/bin/bash
set -euo pipefail

# Run from the MultiResUNet directory on the server:
#   cd ~/zjm/ORO1/ORO/MultiResUNet
#   bash ../temp.sh
#
# If only one GPU is available, run these commands one by one instead of
# launching the whole script.

# 1) Current best recipe + mild class-2 emphasis.
nohup python train.py --validation-split 0.1 --scale --scale-factor 0.75 --input-channels 3 --output-channels 4 --epochs 120 --batch-size 16 --learning-rate 2e-5 --gradient-clip 0.5 --weight-decay 2e-4 --num-workers 4 --prefetch-factor 2 --repeat-factor 1 --train-augmentation --augmentation-strength mild --augmentation-curriculum cosine --curriculum-start-epoch 40 --curriculum-ramp-epochs 35 --curriculum-max-aug-level 0.4 --curriculum-target-strength moderate --verbose --save-model --save-dir models/C_scale075_l04_cls2w15 --tensorboard --log-dir runs/logs/C_scale075_l04_cls2w15 --use-combined-loss --bce-weight 0.7 --dice-weight 0.3 --class-weights 1 1 1.5 1 --lr-scheduler cosine --early-stopping-min-epochs 90 --early-stopping-patience 25 --device cuda --seed 42 > run_C_scale075_l04_cls2w15.log 2>&1 &

# 2) Stronger class-2 emphasis.
nohup python train.py --validation-split 0.1 --scale --scale-factor 0.75 --input-channels 3 --output-channels 4 --epochs 120 --batch-size 16 --learning-rate 2e-5 --gradient-clip 0.5 --weight-decay 2e-4 --num-workers 4 --prefetch-factor 2 --repeat-factor 1 --train-augmentation --augmentation-strength mild --augmentation-curriculum cosine --curriculum-start-epoch 40 --curriculum-ramp-epochs 35 --curriculum-max-aug-level 0.4 --curriculum-target-strength moderate --verbose --save-model --save-dir models/C_scale075_l04_cls2w20 --tensorboard --log-dir runs/logs/C_scale075_l04_cls2w20 --use-combined-loss --bce-weight 0.7 --dice-weight 0.3 --class-weights 1 1 2.0 1 --lr-scheduler cosine --early-stopping-min-epochs 90 --early-stopping-patience 25 --device cuda --seed 42 > run_C_scale075_l04_cls2w20.log 2>&1 &

# 3) Moderate class-2 emphasis plus slightly more Dice loss.
nohup python train.py --validation-split 0.1 --scale --scale-factor 0.75 --input-channels 3 --output-channels 4 --epochs 120 --batch-size 16 --learning-rate 2e-5 --gradient-clip 0.5 --weight-decay 2e-4 --num-workers 4 --prefetch-factor 2 --repeat-factor 1 --train-augmentation --augmentation-strength mild --augmentation-curriculum cosine --curriculum-start-epoch 40 --curriculum-ramp-epochs 35 --curriculum-max-aug-level 0.4 --curriculum-target-strength moderate --verbose --save-model --save-dir models/C_scale075_l04_cls2w15_dice04 --tensorboard --log-dir runs/logs/C_scale075_l04_cls2w15_dice04 --use-combined-loss --bce-weight 0.6 --dice-weight 0.4 --class-weights 1 1 1.5 1 --lr-scheduler cosine --early-stopping-min-epochs 90 --early-stopping-patience 25 --device cuda --seed 42 > run_C_scale075_l04_cls2w15_dice04.log 2>&1 &

# 4) Class-2 emphasis with lower augmentation ceiling.
nohup python train.py --validation-split 0.1 --scale --scale-factor 0.75 --input-channels 3 --output-channels 4 --epochs 120 --batch-size 16 --learning-rate 2e-5 --gradient-clip 0.5 --weight-decay 2e-4 --num-workers 4 --prefetch-factor 2 --repeat-factor 1 --train-augmentation --augmentation-strength mild --augmentation-curriculum cosine --curriculum-start-epoch 40 --curriculum-ramp-epochs 35 --curriculum-max-aug-level 0.35 --curriculum-target-strength moderate --verbose --save-model --save-dir models/C_scale075_l035_cls2w15 --tensorboard --log-dir runs/logs/C_scale075_l035_cls2w15 --use-combined-loss --bce-weight 0.7 --dice-weight 0.3 --class-weights 1 1 1.5 1 --lr-scheduler cosine --early-stopping-min-epochs 90 --early-stopping-patience 25 --device cuda --seed 42 > run_C_scale075_l035_cls2w15.log 2>&1 &

# 5) Class-2 emphasis with slower ramp.
nohup python train.py --validation-split 0.1 --scale --scale-factor 0.75 --input-channels 3 --output-channels 4 --epochs 130 --batch-size 16 --learning-rate 2e-5 --gradient-clip 0.5 --weight-decay 2e-4 --num-workers 4 --prefetch-factor 2 --repeat-factor 1 --train-augmentation --augmentation-strength mild --augmentation-curriculum cosine --curriculum-start-epoch 40 --curriculum-ramp-epochs 50 --curriculum-max-aug-level 0.4 --curriculum-target-strength moderate --verbose --save-model --save-dir models/C_scale075_l04_ramp50_cls2w15 --tensorboard --log-dir runs/logs/C_scale075_l04_ramp50_cls2w15 --use-combined-loss --bce-weight 0.7 --dice-weight 0.3 --class-weights 1 1 1.5 1 --lr-scheduler cosine --early-stopping-min-epochs 100 --early-stopping-patience 25 --device cuda --seed 42 > run_C_scale075_l04_ramp50_cls2w15.log 2>&1 &

# 6) Class-2 emphasis with slightly lower learning rate for late stability.
nohup python train.py --validation-split 0.1 --scale --scale-factor 0.75 --input-channels 3 --output-channels 4 --epochs 130 --batch-size 16 --learning-rate 1.5e-5 --gradient-clip 0.5 --weight-decay 2e-4 --num-workers 4 --prefetch-factor 2 --repeat-factor 1 --train-augmentation --augmentation-strength mild --augmentation-curriculum cosine --curriculum-start-epoch 40 --curriculum-ramp-epochs 35 --curriculum-max-aug-level 0.4 --curriculum-target-strength moderate --verbose --save-model --save-dir models/C_scale075_l04_cls2w15_lr15e5 --tensorboard --log-dir runs/logs/C_scale075_l04_cls2w15_lr15e5 --use-combined-loss --bce-weight 0.7 --dice-weight 0.3 --class-weights 1 1 1.5 1 --lr-scheduler cosine --early-stopping-min-epochs 100 --early-stopping-patience 25 --device cuda --seed 42 > run_C_scale075_l04_cls2w15_lr15e5.log 2>&1 &

# 7) Conservative full-resolution retry: no curriculum, mild augmentation only.
nohup python train.py --validation-split 0.1 --scale --scale-factor 1.0 --input-channels 3 --output-channels 4 --epochs 100 --batch-size 8 --learning-rate 1.5e-5 --gradient-clip 0.5 --weight-decay 2e-4 --num-workers 4 --prefetch-factor 2 --repeat-factor 1 --train-augmentation --augmentation-strength mild --augmentation-curriculum none --verbose --save-model --save-dir models/C_scale100_mild_lr15e5 --tensorboard --log-dir runs/logs/C_scale100_mild_lr15e5 --use-combined-loss --bce-weight 0.7 --dice-weight 0.3 --class-weights 1 1 1.5 1 --lr-scheduler cosine --early-stopping-min-epochs 70 --early-stopping-patience 20 --device cuda --seed 42 > run_C_scale100_mild_lr15e5.log 2>&1 &

# 8) Full-resolution retry with very light curriculum only.
nohup python train.py --validation-split 0.1 --scale --scale-factor 1.0 --input-channels 3 --output-channels 4 --epochs 110 --batch-size 8 --learning-rate 1.5e-5 --gradient-clip 0.5 --weight-decay 2e-4 --num-workers 4 --prefetch-factor 2 --repeat-factor 1 --train-augmentation --augmentation-strength mild --augmentation-curriculum cosine --curriculum-start-epoch 45 --curriculum-ramp-epochs 45 --curriculum-max-aug-level 0.2 --curriculum-target-strength moderate --verbose --save-model --save-dir models/C_scale100_l02_ramp45_cls2w15_lr15e5 --tensorboard --log-dir runs/logs/C_scale100_l02_ramp45_cls2w15_lr15e5 --use-combined-loss --bce-weight 0.7 --dice-weight 0.3 --class-weights 1 1 1.5 1 --lr-scheduler cosine --early-stopping-min-epochs 80 --early-stopping-patience 25 --device cuda --seed 42 > run_C_scale100_l02_ramp45_cls2w15_lr15e5.log 2>&1 &

wait
