#!/bin/bash
set -euo pipefail

# Run from the MultiResUNet directory on the server:
#   cd ~/zjm/ORO1/ORO/MultiResUNet
#   bash ../temp.sh
#
# If using --model-architecture smp_unet, install the optional dependency first:
#   pip install segmentation-models-pytorch
#
# If only one GPU is available, run these one by one instead of launching all jobs.

# 1) Current peak recipe + flip TTA. Fastest test for direct validation/inference lift.
nohup python train.py --validation-split 0.1 --scale --scale-factor 0.75 --input-channels 3 --output-channels 4 --epochs 120 --batch-size 16 --learning-rate 2e-5 --gradient-clip 0.5 --weight-decay 2e-4 --num-workers 4 --prefetch-factor 2 --repeat-factor 1 --train-augmentation --augmentation-strength mild --augmentation-curriculum cosine --curriculum-start-epoch 40 --curriculum-ramp-epochs 35 --curriculum-max-aug-level 0.4 --curriculum-target-strength moderate --verbose --save-model --save-dir models/C_scale075_l04_cls2w125_tta --tensorboard --log-dir runs/logs/C_scale075_l04_cls2w125_tta --use-combined-loss --bce-weight 0.7 --dice-weight 0.3 --class-weights 1 1 1.25 1 --val-tta flips --lr-scheduler cosine --early-stopping-min-epochs 90 --early-stopping-patience 20 --device cuda --seed 42 > run_C_scale075_l04_cls2w125_tta.log 2>&1 &

# 2) Stable class-balanced recipe + flip TTA.
nohup python train.py --validation-split 0.1 --scale --scale-factor 0.75 --input-channels 3 --output-channels 4 --epochs 120 --batch-size 16 --learning-rate 2e-5 --gradient-clip 0.5 --weight-decay 2e-4 --num-workers 4 --prefetch-factor 2 --repeat-factor 1 --train-augmentation --augmentation-strength mild --augmentation-curriculum cosine --curriculum-start-epoch 40 --curriculum-ramp-epochs 35 --curriculum-max-aug-level 0.4 --curriculum-target-strength moderate --verbose --save-model --save-dir models/C_scale075_l04_cls011_cls2w15_tta --tensorboard --log-dir runs/logs/C_scale075_l04_cls011_cls2w15_tta --use-combined-loss --bce-weight 0.7 --dice-weight 0.3 --class-weights 1.1 1.1 1.5 1 --val-tta flips --lr-scheduler cosine --early-stopping-min-epochs 90 --early-stopping-patience 20 --device cuda --seed 42 > run_C_scale075_l04_cls011_cls2w15_tta.log 2>&1 &

# 3) Class-2 data-level oversampling, moderate loss weight.
nohup python train.py --validation-split 0.1 --scale --scale-factor 0.75 --input-channels 3 --output-channels 4 --epochs 120 --batch-size 16 --learning-rate 2e-5 --gradient-clip 0.5 --weight-decay 2e-4 --num-workers 4 --prefetch-factor 2 --repeat-factor 1 --train-augmentation --augmentation-strength mild --augmentation-curriculum cosine --curriculum-start-epoch 40 --curriculum-ramp-epochs 35 --curriculum-max-aug-level 0.4 --curriculum-target-strength moderate --verbose --save-model --save-dir models/C_scale075_l04_cls2w125_os15 --tensorboard --log-dir runs/logs/C_scale075_l04_cls2w125_os15 --use-combined-loss --bce-weight 0.7 --dice-weight 0.3 --class-weights 1 1 1.25 1 --oversample-class-indices 2 --oversample-factor 1.5 --oversample-min-pixels 1 --lr-scheduler cosine --early-stopping-min-epochs 90 --early-stopping-patience 20 --device cuda --seed 42 > run_C_scale075_l04_cls2w125_os15.log 2>&1 &

# 4) Stronger class-2 oversampling, with lower class2 loss weight to avoid over-penalty.
nohup python train.py --validation-split 0.1 --scale --scale-factor 0.75 --input-channels 3 --output-channels 4 --epochs 120 --batch-size 16 --learning-rate 2e-5 --gradient-clip 0.5 --weight-decay 2e-4 --num-workers 4 --prefetch-factor 2 --repeat-factor 1 --train-augmentation --augmentation-strength mild --augmentation-curriculum cosine --curriculum-start-epoch 40 --curriculum-ramp-epochs 35 --curriculum-max-aug-level 0.4 --curriculum-target-strength moderate --verbose --save-model --save-dir models/C_scale075_l04_cls2w11_os20 --tensorboard --log-dir runs/logs/C_scale075_l04_cls2w11_os20 --use-combined-loss --bce-weight 0.7 --dice-weight 0.3 --class-weights 1 1 1.1 1 --oversample-class-indices 2 --oversample-factor 2.0 --oversample-min-pixels 1 --lr-scheduler cosine --early-stopping-min-epochs 90 --early-stopping-patience 20 --device cuda --seed 42 > run_C_scale075_l04_cls2w11_os20.log 2>&1 &

# 5) Oversampling + stronger regularization on the stable class-balanced recipe.
nohup python train.py --validation-split 0.1 --scale --scale-factor 0.75 --input-channels 3 --output-channels 4 --epochs 120 --batch-size 16 --learning-rate 2e-5 --gradient-clip 0.5 --weight-decay 5e-4 --num-workers 4 --prefetch-factor 2 --repeat-factor 1 --train-augmentation --augmentation-strength mild --augmentation-curriculum cosine --curriculum-start-epoch 40 --curriculum-ramp-epochs 35 --curriculum-max-aug-level 0.4 --curriculum-target-strength moderate --verbose --save-model --save-dir models/C_scale075_l04_cls011_cls2w15_os15_wd5e4 --tensorboard --log-dir runs/logs/C_scale075_l04_cls011_cls2w15_os15_wd5e4 --use-combined-loss --bce-weight 0.7 --dice-weight 0.3 --class-weights 1.1 1.1 1.5 1 --oversample-class-indices 2 --oversample-factor 1.5 --oversample-min-pixels 1 --lr-scheduler cosine --early-stopping-min-epochs 90 --early-stopping-patience 20 --device cuda --seed 42 > run_C_scale075_l04_cls011_cls2w15_os15_wd5e4.log 2>&1 &

# 6) Pretrained U-Net, ResNet34 encoder. Main pretrained baseline.
nohup python train.py --model-architecture smp_unet --encoder-name resnet34 --encoder-weights imagenet --validation-split 0.1 --scale --scale-factor 0.75 --input-channels 3 --output-channels 4 --epochs 100 --batch-size 16 --learning-rate 2e-5 --gradient-clip 0.5 --weight-decay 5e-4 --num-workers 4 --prefetch-factor 2 --repeat-factor 1 --train-augmentation --augmentation-strength mild --augmentation-curriculum cosine --curriculum-start-epoch 30 --curriculum-ramp-epochs 30 --curriculum-max-aug-level 0.4 --curriculum-target-strength moderate --verbose --save-model --save-dir models/P_smp_resnet34_cls2w125 --tensorboard --log-dir runs/logs/P_smp_resnet34_cls2w125 --use-combined-loss --bce-weight 0.7 --dice-weight 0.3 --class-weights 1 1 1.25 1 --lr-scheduler cosine --early-stopping-min-epochs 70 --early-stopping-patience 20 --device cuda --seed 42 > run_P_smp_resnet34_cls2w125.log 2>&1 &

# 7) Pretrained ResNet34 + TTA. Slower but directly tests deploy-time best score.
nohup python train.py --model-architecture smp_unet --encoder-name resnet34 --encoder-weights imagenet --validation-split 0.1 --scale --scale-factor 0.75 --input-channels 3 --output-channels 4 --epochs 100 --batch-size 16 --learning-rate 2e-5 --gradient-clip 0.5 --weight-decay 5e-4 --num-workers 4 --prefetch-factor 2 --repeat-factor 1 --train-augmentation --augmentation-strength mild --augmentation-curriculum cosine --curriculum-start-epoch 30 --curriculum-ramp-epochs 30 --curriculum-max-aug-level 0.4 --curriculum-target-strength moderate --verbose --save-model --save-dir models/P_smp_resnet34_cls2w125_tta --tensorboard --log-dir runs/logs/P_smp_resnet34_cls2w125_tta --use-combined-loss --bce-weight 0.7 --dice-weight 0.3 --class-weights 1 1 1.25 1 --val-tta flips --lr-scheduler cosine --early-stopping-min-epochs 70 --early-stopping-patience 20 --device cuda --seed 42 > run_P_smp_resnet34_cls2w125_tta.log 2>&1 &

# 8) Pretrained ResNet34 + class-2 oversampling.
nohup python train.py --model-architecture smp_unet --encoder-name resnet34 --encoder-weights imagenet --validation-split 0.1 --scale --scale-factor 0.75 --input-channels 3 --output-channels 4 --epochs 100 --batch-size 16 --learning-rate 2e-5 --gradient-clip 0.5 --weight-decay 5e-4 --num-workers 4 --prefetch-factor 2 --repeat-factor 1 --train-augmentation --augmentation-strength mild --augmentation-curriculum cosine --curriculum-start-epoch 30 --curriculum-ramp-epochs 30 --curriculum-max-aug-level 0.4 --curriculum-target-strength moderate --verbose --save-model --save-dir models/P_smp_resnet34_cls2w125_os15 --tensorboard --log-dir runs/logs/P_smp_resnet34_cls2w125_os15 --use-combined-loss --bce-weight 0.7 --dice-weight 0.3 --class-weights 1 1 1.25 1 --oversample-class-indices 2 --oversample-factor 1.5 --oversample-min-pixels 1 --lr-scheduler cosine --early-stopping-min-epochs 70 --early-stopping-patience 20 --device cuda --seed 42 > run_P_smp_resnet34_cls2w125_os15.log 2>&1 &

# 9) Pretrained EfficientNet-B3 encoder. Higher-capacity pretrained test; reduce batch if OOM.
nohup python train.py --model-architecture smp_unet --encoder-name efficientnet-b3 --encoder-weights imagenet --validation-split 0.1 --scale --scale-factor 0.75 --input-channels 3 --output-channels 4 --epochs 100 --batch-size 8 --learning-rate 2e-5 --gradient-clip 0.5 --weight-decay 5e-4 --num-workers 4 --prefetch-factor 2 --repeat-factor 1 --train-augmentation --augmentation-strength mild --augmentation-curriculum cosine --curriculum-start-epoch 30 --curriculum-ramp-epochs 30 --curriculum-max-aug-level 0.4 --curriculum-target-strength moderate --verbose --save-model --save-dir models/P_smp_effb3_cls2w125 --tensorboard --log-dir runs/logs/P_smp_effb3_cls2w125 --use-combined-loss --bce-weight 0.7 --dice-weight 0.3 --class-weights 1 1 1.25 1 --lr-scheduler cosine --early-stopping-min-epochs 70 --early-stopping-patience 20 --device cuda --seed 42 > run_P_smp_effb3_cls2w125.log 2>&1 &

# 10) Same SMP ResNet34 architecture without pretrained weights. Control for architecture vs pretraining.
nohup python train.py --model-architecture smp_unet --encoder-name resnet34 --encoder-weights none --validation-split 0.1 --scale --scale-factor 0.75 --input-channels 3 --output-channels 4 --epochs 100 --batch-size 16 --learning-rate 2e-5 --gradient-clip 0.5 --weight-decay 5e-4 --num-workers 4 --prefetch-factor 2 --repeat-factor 1 --train-augmentation --augmentation-strength mild --augmentation-curriculum cosine --curriculum-start-epoch 30 --curriculum-ramp-epochs 30 --curriculum-max-aug-level 0.4 --curriculum-target-strength moderate --verbose --save-model --save-dir models/P_smp_resnet34_random_cls2w125 --tensorboard --log-dir runs/logs/P_smp_resnet34_random_cls2w125 --use-combined-loss --bce-weight 0.7 --dice-weight 0.3 --class-weights 1 1 1.25 1 --lr-scheduler cosine --early-stopping-min-epochs 70 --early-stopping-patience 20 --device cuda --seed 42 > run_P_smp_resnet34_random_cls2w125.log 2>&1 &

wait
